config/routes.rb
Rails.application.routes.draw do

  root "messages#index"

  devise_for :users
  resources :messages

  resources :users

end

app/models/message.rb
class Message < ActiveRecord::Base

  belongs_to :user

  validates :latitude, presence: true
  validates :longitude, presence: true
  validates :content, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :messages

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def full_name
    "#{self.first_name} #{self.last_name}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)

    @message.user_id = user_signed_in? ? current_user.id : nil

    respond_to do |format|
      if @message.save
        format.html { redirect_to messages_path, notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:content, :latitude, :longitude)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # # GET /users
  # # GET /users.json
  # def index
  #   @users = User.all
  # end

  # # GET /users/1
  # # GET /users/1.json
  # def show
  # end

  # # GET /users/new
  # def new
  #   @user = User.new
  # end

  # GET /users/1/edit
  def edit
    render 'users/edit'
  end

  # # POST /users
  # # POST /users.json
  # def create
  #   @user = User.new(user_params)

  #   respond_to do |format|
  #     if @user.save
  #       format.html { redirect_to @user, notice: 'User was successfully created.' }
  #       format.json { render :show, status: :created, location: @user }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @user.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to edit_user_path(id: @user), notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
      raise "Not current user" if @user.id != current_user.id || !user_signed_in?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<!-- Fixed navbar -->
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">ระบาย</a>
    </div>


    <div id="navbar" class="navbar-collapse collapse">

      <ul class="nav navbar-nav navbar-right">


        <li><%= link_to "Post Message", new_message_path %></li>
        <li><%= link_to "All Messages", messages_path %></li>

        <% if user_signed_in? %>
          <li><%= link_to "My Messages", "#" %></li>
          <li><%= link_to "Profile", edit_user_path(id: current_user.id) %></li>
          <li><%= link_to "#{current_user.full_name} (Logout!)", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>

      </ul>
    </div>


  </div>
</nav>

app/views/layouts/_shim.html.erb
<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Rabuy</title>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= render 'layouts/shim' %>
    <%= csrf_meta_tags %>


    <%= yield :js_html %>
    <script>
      <%= yield :js %>
    </script>

  </head>

  <body>

    <%= render 'layouts/header' %>

    <div class="container">
      <%= yield %>
    </div>


    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  </body>
</html>

app/views/messages/_form.html.erb
<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content, class: "form-control" %>
  </div>

  <%= f.hidden_field :latitude %>
  <%= f.hidden_field :longitude %>

  <div class="actions">
    <%= f.submit "POST", class: "btn btn-success pull-right" %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<% content_for :js_html do %>
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp"></script>
<% end %>
<script>
<% content_for :js do %>
  var map;

  function addMarker(content,time_string,lat,lng){
    var contentString = content;
    var infowindow = new google.maps.InfoWindow({
      content: contentString
    });
    var marker = new google.maps.Marker({
      position: new google.maps.LatLng(lat, lng),
      map: map,
      title: time_string
    });
    google.maps.event.addListener(marker, 'click', function() {
      infowindow.open(map,marker);
    });
  }

  function initialize(lat,lng) {
    var mapOptions = {
      zoom: 15,
      center: new google.maps.LatLng(lat, lng)
    };
    map = new google.maps.Map(document.getElementById('map-canvas'),
        mapOptions);

    <% @messages.each do |m| %>
      addMarker("<%= m.content %>", "<%= m.created_at.to_s %>", <%= m.latitude.to_f %>, <%= m.longitude.to_f %>)
    <%end%>
  }

  navigator.geolocation.getCurrentPosition(function(location){
    console.log(location)
    initialize(location.coords.latitude,location.coords.longitude);
  })

<% end %>
</script>


<div id="map-canvas"></div>

app/views/messages/new.html.erb
<div id="map-canvas"></div>

<% content_for :js_html do %>
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp"></script>
<% end %>

<script>
<% content_for :js do %>

  var map;

  var form = "<%= escape_javascript(render 'form') %>";

  function addMarker(content,lat,lng){
    var contentString = content;
    var infowindow = new google.maps.InfoWindow({
      content: contentString
    });
    var marker = new google.maps.Marker({
      position: new google.maps.LatLng(lat, lng),
      map: map,
      title: ""
    });
    infowindow.open(map,marker);
    google.maps.event.addListener(infowindow, 'domready', function(){
      $('#message_latitude').val(lat)
      $('#message_longitude').val(lng)
    });
  }

  function initialize(lat,lng) {
    var mapOptions = {
      zoom: 15,
      center: new google.maps.LatLng(lat, lng)
    };
    map = new google.maps.Map(document.getElementById('map-canvas'),
        mapOptions);

    addMarker(form, lat, lng)
  }

  navigator.geolocation.getCurrentPosition(function(location){
    console.log(location)

    initialize(location.coords.latitude,location.coords.longitude);

  })


<% end %>
</script>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @message.content %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @message.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @message.longitude %>
</p>

<p>
  <strong>User:</strong>
  <%= @message.user_id %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit "Update Profile", class: "btn btn-success pull-right" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="row">
  <div class="col-md-2"></div>
  <div class="col-md-8">
    <h1>Edit Profile</h1>
    <%= render 'users/form' %>
  </div>
  <div class="col-md-2"></div>
</div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>